### PR TITLE
Remove incorrect documentation and assume pointer is not null in GlobalAlloc::dealloc

### LINKED ISSUE #143: Is sdallocx safe to call with a null pointer?
With recent changes to an application, I am running into the error `memory allocation of n bytes failed` (where n is a small number eg. 5, 1, 4) when using `jemallocator`. The application works fine when using the system allocator.

Running `jemalloc` in debug mode reveals that it is failing the [assert](https://github.com/jemalloc/jemalloc/blob/61efbda7098de6fe64c362d309824864308c36d4/src/jemalloc.c#L2980) that `sdallocx` was not called with a null pointer.

The [`jemalloc-sys` docs](https://docs.rs/jemalloc-sys/0.3.2/jemalloc_sys/fn.sdallocx.html) imply it is safe to call `sdallocx` with a null pointer (it states "no action occurs"). I cannot find anything in `jemalloc` docs to confirm this, and by the assert in the code it appears as if it is explicitly not allowed.

Modifying `sdallocx` to simply return when called with a null pointer appears to fix the issue, but I am not sure of the ramifications of this change.

I apologize for not having a minimal example with which to replicate. The scenario in which the error occurs is fairly involved.

### PR DESCRIPTION
**Pull request by davidMcneil**
Resolves #143

### CODE REVIEW

File: jemalloc-sys/src/lib.rs [hunk 1]
```diff
@@ -366,8 +366,6 @@ extern "C" {
     ///
     /// This makes the space available for future allocations.
     ///
-    /// If `ptr` is null, no action occurs.
-    ///
     /// # Safety
     ///
     /// The behavior is _undefined_ if:
```
Comment (gnzlbg) [inline jemalloc-sys/src/lib.rs]: We probably need to add to these lists that the behavior is undefined if the pointer is null in both cases.

**Comment by gnzlbg** [comment]
Thank you!

File: jemalloc-sys/src/lib.rs (hunk 1 above)
Comment (davidMcneil) [reply jemalloc-sys/src/lib.rs:371]: Addressed in [ffdcf7](https://github.com/gnzlbg/jemallocator/pull/144/commits/ffdcf7b62e253868b30ab5ebfed64f16747031de)
